### ISSUE TITLE
{{ parent() }} in root/templates/components/dashboard/navbar.html.twig breaks UI

### ISSUE THREAD

**Issue by brunomnsilva** [userfrosting/UserFrosting#641]
This is noticeable in smaller screens, e.g., smartphone (used chromium developer tools).
The mentioned file creates a new navbar in the DOM and it does not allow to access the sidemenu options, because it overlaps the toggle buttom previously set in the parent twigs.

Suggested fix is to add a new empty block to @admin/components/dashboard/navbar.html.twig to be extended by root/templates/components/dashboard/navbar.html.twig.

This twig only adds a "LOGIN WITH ROOT ACCOUNT" to the navbar.

**Comment by brunomnsilva** [comment]
Current UI: 
![prior-fix](https://cloud.githubusercontent.com/assets/16222114/22691346/f3e75aea-ed31-11e6-90e3-ddb15c070fd2.png)

After proposed fix:
![after-fix](https://cloud.githubusercontent.com/assets/16222114/22691351/fd8860d0-ed31-11e6-8d11-c136e72a1847.png)

**Comment by lcharette** [comment]
The root message should actually be hidden on small width devices.

**Comment by brunomnsilva** [comment]
Don't see any code that would impose that. Nevertheless, the current twig structure breaks the UI the same. 

Proposed fix in `admin/components/dashboard/navbar.html.twig`:
```
{% block dashboard_navbar %}
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- additional elements (e.g., menus, messages) before the user account drop down -->
          {% block dashboard_navbar_extra %} {% endblock %}
          <!-- User Account: style can be found in dropdown.less -->
          {% include "components/user-card.html.twig" %}
        </ul>
    </div>
{% endblock %}
```

Proposed fix in `root/templates/components/dashboard/navbar.html.twig`:
```
{% extends "@admin/components/dashboard/navbar.html.twig" %}

{% block dashboard_navbar_extra %}
  <li><a href="#">{{ translate("HEADER_MESSAGE_ROOT") | upper }}</a></li>
{% endblock %}

```

**Comment by lcharette** [comment]
It's not hidden currently, but it should be as a different locale could display a longer string that would be wrapped on two or more line anyway (for example French: `VOUS ÊTES CONNECTÉ EN TANT QUE L'UTILISATEUR ROOT`).

Can you submit a pull request with the proposed changes?

**Comment by brunomnsilva** [comment]
Done!

**Comment by lcharette** [comment]
PR Merged !

Like I said, there's still an issue when the locale is set to french as the string is longer and make things warp on more than one line. I'll just hide it on mobile for now.

![capture d ecran 2017-02-07 a 16 48 35](https://cloud.githubusercontent.com/assets/2566513/22713167/58f7e288-ed55-11e6-8d46-9b9fd991e730.png)

**Comment by lcharette** [comment]
There we go. Tested on different screen size using Safari Responsive Design Mode ;)

**Comment by brunomnsilva** [comment]
I understand, but that isn't that a corner case? Other solutions would be a
shorter translation, or the use of the twig slice filter to cap longer
strings.

**Comment by lcharette** [comment]
Other situation will require a more sophisticated fix, I agree, but as far as the root message goes, I guess it's enough. That string shouldn't be seen by many users (well, one actually).

For the best user experience on a mobile size, icons should be used anyway
